name = "ACRE-Persistence"
prefix = "l6AA"
author = "16 Air Assault Milsim Community"
mainprefix = "z"

[files]
include = [
    "mod.cpp",
    "meta.cpp",
    "*.paa"
]

[version]
git_hash = 0 # Disabled
path = "addons/main/script_version.hpp"
